### ISSUE TITLE
Convert schemas to TypeScript types

### ISSUE THREAD

**Issue by opl-** [esamarathon/mq-events#7]
Using the standardized JSON schema format allows us to convert the schemas into TypesScript types, which could ease development of other software within the organization.

In order to achieve that, however, several questions have to be answered:

**How will the types be generated?**

- Using [json-schema-to-typescript](https://www.npmjs.com/package/json-schema-to-typescript)
    - Some events like `NodeCG/SCTimerChange` cannot be correctly converted to types because of [this](https://github.com/bcherny/json-schema-to-typescript/issues/243) issue.
- Other?

**How will they be published/used?**

- As an [NPM package](https://www.npmjs.com/)
- Through [GitHub Packages](https://help.github.com/en/github/managing-packages-with-github-packages/configuring-npm-for-use-with-github-packages)
- As a [GitHub branch](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies)

**Comment by opl-** [comment]
To clarify, per zoton's request, the issue with `json-schema-to-typescript` and the `NodeCG/SCTimerChange` event is that the `teamID` property only exists when the value of the `desc` field is equal to either `team_finished` or `team_undid_finish`.

This could be described using JSON Schema with an `anyOf` declaration, where either `desc` is equal to one of the mentioned values and the `teamID` property is required, or where `desc` is equal to any of the other valid values and the `teamID` property doesn't exist. Here's a simplified example (you can play around with it [here](https://www.jsonschemavalidator.net/)):

```json
{
	"required": ["desc", "timer"],
	"properties": {
		"timer": {
			"type": "string"
		}
	},
	"anyOf": [{
		"properties": {
			"desc": {
				"type": "string",
				"enum": ["started"]
			}
		},
		"propertyNames": {
			"enum": ["desc", "timer"]
		}
	}, {
		"required": ["teamID"],
		"properties": {
			"desc": {
				"type": "string",
				"enum": ["team_finished"]
			},
			"teamID": {
				"type": "string"
			}
		},
		"propertyNames": {
			"enum": ["desc", "teamID", "timer"]
		}
	}]
}

```

The problem is that the package in question doesn't correctly support the `anyOf` declaration and so the types it generates would be inaccurate. The current schema bypasses that by simplifying the schema, but because of that the `teamID` property has to be explicitly declared as not undefined or TypeScript will complain ([playground link](https://www.typescriptlang.org/play/?ssl=15&ssc=2&pln=7&pc=1#code/JYOwLgpgTgZghgYwgAgMoGEAqwC210AWcIA5hACbIDeAUMsuRAM4IBcyARE2HFJOR2QAfTpDg4A+jFDAmBChwDcdZGJwBJACIB+dtyigSy+mFzQ9YA6WUBfGjRgBXEAlMB7EMlmpLhgBSgAA6OYBZWJACU1Mh2CB7cyDhMJOwY2HhQhMRklAC81Iws7BxqUjJyCgA0qhDiWsUAjBzVphmNrAAMHRw2ysAwyH5JJAB0hQjIuVPIAOSl0iCy8uQzUbT09AD0m8iYAJ6BEKgIBoFgyADuwAA218hxOIHXcKDIAEYQCHCOTChg8qoDswGB45sgSI5eMRIH8iOcAAZqLTwy43O4fBgQBYUVgqejeXykIbJEZIzQRYwbbbIADqbigAGteG5nOQmLiNl4BsTRmSogTwjzSbUNOTFMhqQBVEAgT7MJi8G57ZAAN2gbzcvzxXiYPkFw2FdU0AEIKRKdgB5Q6eMBuHVMRzA15fX7INwDJxgRxQFCBKBuW1xO4IIikZg0GxAA)):

```typescript
interface SCTimerChanged {
    desc: "started" | "team_finished";
    teamID?: string;
    timer: string;
}

function isString(input: string) {}
const msg: SCTimerChanged = {desc: "team_finished", teamID: "1", timer: "1:00"};
if (msg.desc === 'team_finished') {
    // TypeScript will complain because the types don't guarantee that `teamID` will be defined:
    isString(msg.teamID);
    // Workarounds:
    if (msg.teamID) isString(msg.teamID); // Unnecessarily verbose
    isString(msg.teamID!); // Open to issues in case of future protocol changes
}
```

With a proper schema, the generated types would make it clear that the `teamID` property has to exist for certain `desc` values, preventing us from having to explicitly state that in our code ([playground link](https://www.typescriptlang.org/play/?ssl=1&ssc=1&pln=15&pc=2#code/C4TwDgpgBAygwgFQJYFsICc4AsCGA7AcwgBMoBeKAbwCgo6phUMAuKAZ2HSUIG5qBfKADIoAChr0oxCGwDGrAEQcc6YCQV9BAHyq160uYrU4UAfQBm3JGyzq+k4ygCSAEVYcuvAQEo+1cwCueLKMAPZ4UNYwnNwEotxgAcDuMYTeVPzUsuEcUChsBKzwyGiYuIQk5FQG8lAKjhZWNuoANAwQJq6KAIwKbYylPcwADMMK-HxI5mL5BAB0NeRkFADkDZZ41rbEK+kS9AD0B1AI4BAwslxgwFAA7kgANg9QeKE32ShgDzjcbThs7U6LiguABwFCUAgAA9rMA9HQoqk4rM5o5XL4BEA)):

```typescript
type SCTimerChanged = {
    timer: string;
} & ({
    desc: "started";
} | {
    desc: "team_finished";
    teamID: string;
});
```

**Comment by zoton2** [comment]
Ah OK I understand now, it's just as the schema was already changed I could not tell. So this is a minor issue and nothing breaking then? I think in such case we should just use `json-schema-to-typescript` as in all my other projects I've had success with it, and maybe it can be fixed in the future?

**Comment by opl-** [comment]
Yeah, it's inconvenient and imprecise, but not breaking. That said, unless something new popped up since the issue was opened, `json-schema-to-typescript` is most likely the best option right now.

One possible workaround we could explore would be to manually write some of the more complex types for schemas that require it.

**Comment by zoton2** [comment]
I didn't fully check the typings I had generated besides a minor skim, but I use the library with NodeCG schemas all the time and didn't experience any issues yet.

**Comment by zoton2** [comment]
We've now merged the related PR but there's no separate release yet besides it just being in this repository. I'll close it for now, if anyone else thinks it should be reopened feel free.
