### ISSUE TITLE
Allow reusing JSON schemas from other projects

### ISSUE THREAD

**Issue by opl-** [esamarathon/mq-events#8]
Some projects, like [Speedcontrol](https://github.com/speedcontrol/nodecg-speedcontrol/tree/master/schemas), already make use of JSON Schema. Somehow reusing those instead of repeating in this repository should make for easier maintenance.

There are several methods of achieving this, [as previously mentioned in the PR](https://github.com/esamarathon/mq-events/pull/6#issuecomment-560512563), and one needs to be chosen:

- References to (tagged?) rawgithub URLs
    - Seems reasonable, as long as the tooling supports it. Credit to zoton for the suggestion.
- git submodules
    - Seems a little overkill to clone entire repos just to reference a few schemas in them, but might have better compatibility than using URLs

**Comment by zoton2** [comment]
As I'm not sure how many people are actually using these event schemas with automated tools besides me, I've gone with the URL method, but I've only put it in the `types` branch for now (which I plan to open a PR for soon). URL works fine for `json-schema-to-typescript` which is the tool I use.

**Comment by zoton2** [comment]
Going to close this for now as the related PR is now merged.
